// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sharingvisionbe/ent/post"
	"sharingvisionbe/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[1].Descriptor()
	// post.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	post.TitleValidator = postDescTitle.Validators[0].(func(string) error)
	// postDescCategory is the schema descriptor for category field.
	postDescCategory := postFields[3].Descriptor()
	// post.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	post.CategoryValidator = postDescCategory.Validators[0].(func(string) error)
	// postDescCreatedDate is the schema descriptor for created_date field.
	postDescCreatedDate := postFields[5].Descriptor()
	// post.DefaultCreatedDate holds the default value on creation for the created_date field.
	post.DefaultCreatedDate = postDescCreatedDate.Default.(func() time.Time)
	// post.UpdateDefaultCreatedDate holds the default value on update for the created_date field.
	post.UpdateDefaultCreatedDate = postDescCreatedDate.UpdateDefault.(func() time.Time)
}
